### ISSUE TITLE
Support Gnome Desktop Enviroment

### ISSUE THREAD

**Issue by k0bra3390** [the-root-user/Sweet-HTB#1]
I wanted to ask you if sooner or later you will update the repo to also support the gnome desktop environment

**Comment by the-root-user** [comment]
Hi there,

Earlier, KDE was my go-to DE. Customizing for other DEs seemed a bit too much work. Though later, as I moved to MATE and then GNOME (the current one), I felt the need, and now, there you have it!
GTK, GNOME Shell, and GNOME Apps support has been included in the theme now.

Thanks for your support. Enjoy it :green_heart:

**Comment by k0bra3390** [comment]
I tried to install it on my system, but I'm getting this error:

system info:

![Screenshot from 2024-12-27 17-11-27](https://github.com/user-attachments/assets/10afdb2b-63bf-41dd-9b7a-628d716e53c7)

Error:

```shell

┌─────────────────────────────────────────────┐

   Sweet-HTB - Sweet theme for Sweet Hackers   

   Made with ❤️ by Signore                     

└─────────────────────────────────────────────┘

┌─ Installing..
├── KDE theme
├── Kvantum theme
├── Wallpapers
├── GTK theme
├── Gnome shell theme
├── Gnome apps (libadwaita) theme
├── Plank dock theme
├── SDDM login theme
│    Please provide [sudo] password for k0bra3390: 
├── Albert launcher theme
│
└─ Installation done.

┌─ Do You want to apply the theme? (y/n) y
│  Applying theme..../install.sh: line 181: plasma-apply-wallpaperimage: command not found
sed: can't read /home/k0bra3390/.config/kscreenlockerrc: No such file or directory
sed: can't read /home/k0bra3390/.config/kscreenlockerrc: No such file or directory
sed: can't read /home/k0bra3390/.config/kdeglobals: No such file or directory
sed: can't read /home/k0bra3390/.config/kdeglobals: No such file or directory
sed: can't read /home/k0bra3390/.config/kdedefaults/ksplashrc: No such file or directory
sed: can't read /home/k0bra3390/.config/kdedefaults/kscreenlockerrc: No such file or directory
sed: can't read /home/k0bra3390/.config/kdedefaults/kwinrc: No such file or directory
sed: can't read /home/k0bra3390/.config/lattedockrc: No such file or directory
sed: can't read /home/k0bra3390/.config/konsolerc: No such file or directory
sed: can't read /etc/sddm.conf.d/kde_settings.conf: No such file or directory
 Applied.
└─ ^ Bye ^
```

**Comment by the-root-user** [comment]
You shouldn't worry about it, it got installed successfully for Gnome. Please apply the theme from gnome-tweaks.

It is trying to make some configs for KDE. My apologies, as I have multiple DEs, so even when I was on Gnome, this issue didn't arise for me. I will fix it in the next commit.

**Comment by the-root-user** [comment]
It's been fixed :)
