### ISSUE TITLE
dark reader import 

### ISSUE THREAD

**Issue by Raafay892** [the-root-user/Sweet-HTB#2]
![image](https://github.com/user-attachments/assets/12b54270-6b28-4845-8df3-f5e226d9e786)
issues arises while importing json file in dark reader

**Comment by the-root-user** [comment]
Setting file broke because of the extension's version upgrade.

Fixed and looks like this now. Enjoy.
![a](https://raw.githubusercontent.com/the-root-user/Sweet-HTB/refs/heads/main/dark-reader.png)
